package cn.dyan.mybatis.mapper;

import cn.dyan.mybatis.domain.TbUser;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

public interface TbUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated Wed Sep 27 15:32:32 CST 2017
     */
    @Insert({
        "insert into tb_user (uuid, uname)",
        "values (#{uuid,jdbcType=VARCHAR}, #{uname,jdbcType=VARCHAR})"
    })
    int insert(TbUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated Wed Sep 27 15:32:32 CST 2017
     */
    @Select({
        "select",
        "uuid, uname",
        "from tb_user",
        "order by age desc,username asc"
    })
    @Results({
        @Result(column="uuid", property="uuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="uname", property="uname", jdbcType=JdbcType.VARCHAR)
    })
    List<TbUser> selectAll();
}