package cn.dyan.mybatis.domain;

public class TbUser{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.uuid
     *
     * @mbggenerated Wed Sep 27 15:32:32 CST 2017
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.uname
     *
     * @mbggenerated Wed Sep 27 15:32:32 CST 2017
     */
    private String uname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.uuid
     *
     * @return the value of tb_user.uuid
     *
     * @mbggenerated Wed Sep 27 15:32:32 CST 2017
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.uuid
     *
     * @param uuid the value for tb_user.uuid
     *
     * @mbggenerated Wed Sep 27 15:32:32 CST 2017
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.uname
     *
     * @return the value of tb_user.uname
     *
     * @mbggenerated Wed Sep 27 15:32:32 CST 2017
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.uname
     *
     * @param uname the value for tb_user.uname
     *
     * @mbggenerated Wed Sep 27 15:32:32 CST 2017
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }
}